source 'https://cdn.cocoapods.org/'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

workspace 'ApesterKit.xcworkspace'

project 'ApesterKit.xcodeproj'

platform :ios, '13.0'

use_frameworks!

target 'ApesterKit_Example' do
  pod 'ApesterObjcBridging', :path => '../' ;
  pod 'ApesterKit'         , :path => '../' , :appspecs => ['zHostApp'] , :testspecs => ['zUnitTests','zUITests'];
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end
