# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ApesterTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ApesterTestApp
  pod 'ApesterKit'
  target 'ApesterTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApesterTestAppUITests' do
    # Pods for testing
  end

end
